Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 735, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/cli.py", line 903, in prepare_and_parse_args
    return helpful.parse_args()
  File "/usr/lib/python2.7/site-packages/certbot/cli.py", line 367, in parse_args
    parsed_args = self.parser.parse_args(self.args)
  File "/usr/lib/python2.7/site-packages/configargparse.py", line 402, in parse_args
    env_vars = env_vars)
  File "/usr/lib/python2.7/site-packages/configargparse.py", line 556, in parse_known_args
    self, args=args, namespace=namespace)
  File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 271, in __call__
    namespace.webroot_path.append(_validate_webroot(webroot_path))
  File "/usr/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 284, in _validate_webroot
    raise errors.PluginError(webroot_path + " does not exist or is not a directory")
PluginError: /srv/nginx/couchpotato.dray.be does not exist or is not a directory
